name: Testing E2E - coredns

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DNS_SERVER_IP: "127.0.0.1"
  DNS_SERVER_PORT: "5553"

jobs:
  coredns:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        coredns: [ '1.8.4', '1.8.5' ]
        python: [ '3.8', '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: {{ $matrix.python }}

    - name: Deploy coredns docker image
      run: |
        sudo docker run -d --network="host" --name=coredns -v $PWD/tests/:$PWD/tests/ coredns/coredns:{{ $matrix.coredns }} -conf $PWD/tests/coredns-tcp
        sudo docker logs coredns > /tmp/core.out
        sudo cat /tmp/core.out
        
    - name: Run Python tests 
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m pip install --upgrade dnspython protobuf
        sudo -E python3 -m unittest tests.test_receiver_tcpsocket -v
